language: python
matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=about
    - python: 3.7
      env: TOXENV=sa
    - python: 3.7
      env: TOXENV=sphinx
    - python: 2.7
      env: TOXENV=py27 TEST_QUICK=1 COVERAGE_ID=travis-ci
    - python: 3.4
      env: TOXENV=py34 TEST_QUICK=1 COVERAGE_ID=travis-ci
    - python: 3.5
      env: TOXENV=py35 TEST_QUICK=1 COVERAGE_ID=travis-ci
    - python: 3.6
      env: TOXENV=py36 COVERAGE_ID=travis-ci
    - python: 3.7
      env: TOXENV=py37 COVERAGE_ID=travis-ci
    - python: 3.8
      env: TOXENV=py38 COVERAGE_ID=travis-ci
    - python: 3.9-dev
      env: TOXENV=py39 COVERAGE_ID=travis-ci

jobs:
  allow_failures:
  - python: 3.9-dev

install:
  - pip install tox
script:
  - tox
sudo: false

notifications:
  email:
    recipients:
      - contact@jeffquast.com
    on_success: change
    on_failure: change
#  irc:
#    channels:
#      - "irc.servercentral.net#1984"
#    template:
#      - "%{repository}(%{branch}): %{message} (%{duration}) %{build_url}"
#    skip_join: true
#    on_success: change
#    on_failure: change
