language: python
matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOXENV=py27,codecov TEST_QUICK=1 COVERAGE_ID=travis-ci
    - python: 3.4
      env: TOXENV=py34,codecov TEST_QUICK=1 COVERAGE_ID=travis-ci
    - python: 3.5
      env: TOXENV=py35,codecov TEST_QUICK=1 COVERAGE_ID=travis-ci
    - python: 3.6
      env: TOXENV=py36,codecov TEST_QUICK=1 COVERAGE_ID=travis-ci
    - python: 3.7
      env: TOXENV=py37,codecov TEST_QUICK=1 COVERAGE_ID=travis-ci
    - python: 3.8
      env: TOXENV=py38,codecov COVERAGE_ID=travis-ci
    - python: 3.9-dev
      env: TOXENV=py39,codecov TEST_QUICK=1 COVERAGE_ID=travis-ci
    - python: 3.8
      env: TOXENV=about,pylint,flake8,flake8_tests,sphinx COVERAGE_ID=travis-ci
    - python: 3.8
      os: windows
      language: shell
      before_install:
         - choco install python --version 3.8.0
         - python -m pip install --upgrade pip
         - python -m pip install tox
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH TOXENV=py38,codecov COVERAGE_ID=travis-ci TEST_KEYBOARD=no

jobs:
  allow_failures:
    - env: TOXENV=py39,codecov TEST_QUICK=1 COVERAGE_ID=travis-ci
    - env: TOXENV=about,pylint,flake8,flake8_tests,sphinx COVERAGE_ID=travis-ci

install:
  - pip install tox
script:
  - tox
sudo: false

notifications:
  email:
    recipients:
      - contact@jeffquast.com
    on_success: change
    on_failure: change
